name: flutter_bluttooth_debugging
description: Bluetooth debugging tool fo Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  # 加载更多
  pull_to_refresh: ^1.6.3
  flutter_blue: ^0.7.3
  # UUID
  uuid: ^2.2.2
  base:
    path: ../simple/base
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/

